backend/src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('news.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('data/', include('lessons.urls', namespace='data'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/src/lessons/urls.py
from django.urls import path

from .views import add_lecture, add_review, delete_lecture, delete_review, LectureDetail, SchedulesView


app_name = 'data'

urlpatterns = [
    path('add_lecture/', add_lecture, name='add_lecture'),
    path('add_review/<int:pk>/', add_review, name='add_review'),
    path('delete_lecture/<int:lecture_id>/', delete_lecture, name='delete_lecture'),
    path('delete_review/<int:review_id>/', delete_review, name='delete_review'),
    path('lecture/<int:pk>/', LectureDetail.as_view(), name='lecture_detail'),
    path('schedules/', SchedulesView.as_view(), name='schedules'),
]

backend/src/news/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, NewsView, NewsDetailView



urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('news/', NewsView.as_view(), name='news'),
    path('news/<slug:slug>/', NewsDetailView.as_view(), name='news_detail'),
]

backend/src/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (UserProfileView, login,
                    logout, TeacherProfile,
                    AllTeachers, PublicTeacherProfile,
                    add_personal_link, delete_personal_link,
                    delete_link)


app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('teacher-profile/<int:teacher_id>/', TeacherProfile.as_view(), name='teacher_profile'),
    path('add_personal_link/', add_personal_link, name='add_personal_link'),
    path('delete_personal_link/<int:link_id>/', delete_personal_link, name='delete_personal_link'),
    path('delete_link/<int:link_id>/', delete_link, name='delete_link'),
    path('all_teachers/', AllTeachers.as_view(), name='blog'),
    path('public_profile_teacher/<int:teacher_id>/', PublicTeacherProfile.as_view(), name='public_profile'),
    path('logout/', logout, name='logout'),
]

backend/src/templates/includes/footer.html
{% load static %}


<footer class="footer">
    <div class="footer_content">
        <div class="footer_contacts">
            <h1 class="footer_contacts_title">Контакты</h1>
            <div class="footer_location">
                <img src="{% static 'src/images/location.svg' %}" alt="метка">
                <p>367000, Россия, Республика Дагестан, г. Махачкала,<br>ул. Дзержинского, 21</p>
            </div>
            <div class="footer_feedback">
                <h2 style="color: #fff">8 (722) 67-42-65</h2>
                <a href="mailto:collegedsu@mail.ru">collegedsu@mail.ru</a>
                <h2 style="color: #fff; margin-top: 20px">Created by:</h2>
                <h2 style="color: #fff; font-size: 16px; line-height: 20px;">Гасанбеков Абужапар</h2>
                <h2 style="color: #fff; font-size: 16px; line-height: 20px;">Ибрагимов Забит</h2>
                <h2 style="color: #fff; font-size: 16px; line-height: 20px;">Шафиев Саид</h2>
            </div>
            <div class="footer_messenger">
                <a class="footer_telegram" href="https://t.me/colledgedsu"><img id="footer_telegram" src="{% static 'src/images/telegram.svg' %}" alt="телеграм"></a>
                <a class="footer_vk" href="https://vk.com/mediaclubcollegedgu"><img id="footer_vk" src="{% static 'src/images/vk.svg' %}" alt="вк"></a>
            </div>
        </div>
        <div class="footer_line" id="footer_line"></div>
        <div class="footer_info">
            <div class="footer_info_cont1">
                <div class="cont1_top_block">
                    <ul class="cont1_students">
                        <h1 class="cont1_title">Студентам</h1>
                        {% if user.is_authenticated %}
                            <li class="cont1_students_item"><a href="{% url 'data:schedules' %}">Расписание</a></li>
                        {% else %}
                            <li class="cont1_students_item"><a href="https://raspisanie.dgu.ru/">Расписание</a></li>
                        {% endif %}
                        <li class="cont1_students_item"><a href="https://login.dnevnik.ru/login">Электронный журнал</a></li>
                        <li class="cont1_students_item">
                            {% if user.is_authenticated %}
                                <a href="{% url 'users:profile' user.id%}">
                                    Профиль
                                </a>
                            {% else %}
                                <a href="{% url 'users:login' %}">
                                    Профиль
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                    <ul class="cont1_applicants">
                        <h1 class="cont1_title">Абитуриентам</h1>
                        <li class="cont1_students_item"><a href="https://dgu.ru/Abitur/?id=15252">Прием 2023</a></li>
                    </ul>
                </div>
                <div class="cont1_bottom_block">
                    <ul class="cont1_education">
                        <h1 class="cont1_title">Образование</h1>
                        <li class="cont1_students_item"><a href="">Сессия</a></li>
                        <li class="cont1_students_item"><a href="">Полезные ссылки</a></li>
                    </ul>
                    <iframe class="main_map" src="https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d1459.488594269916!2d47.49721647124244!3d42.97875416425313!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNDLCsDU4JzQzLjUiTiA0N8KwMjknNTIuNyJF!5e0!3m2!1sru!2sru!4v1694902873032!5m2!1sru!2sru" width="700px" height="300px" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </div>
</footer>

backend/src/templates/includes/header.html
{% load static %}


<header class="registration_header">
    <div class="header_navbar" id="header_navbar">
        <div class="nav_left_path">
            <h1><a style="color: #fff;" href="/">Колледж ДГУ</a></h1>
            <div class="header_burger" id="header_burger"></div>
        </div>
        <ul style="width: 55%;" class="nav_right_path" id="nav_right_path">
            <li><a href="/">Главная</a></li>
            {% if user.is_teacher %}
                <li><a href="{% url 'users:teacher_profile' user.id %}">Для преподавателя</a></li>
            {% endif %}
            <li><a href="/news">Новости</a></li>
            <li><a href="{% url 'data:schedules' %}">Расписание</a></li>
            {% if user.is_authenticated %}
                {% if not user.is_teacher %}
                    <li><a href="https://bitrix.dgu.ru/eios/Svedeniya-ob-EIOS-bibl.pdf">Библ. ресурсы</a></li>
                    <li><a href="{% url 'users:blog' %}">Преподаватели</a></li>
                {% endif %}
                <li><a style="color: #fff;" href="{% url 'users:profile' user.id%}">Профиль</a></li>
            {% else %}
                <li><a style="color: #fff;" href="{% url 'users:login' %}">Вход</a></li>
            {% endif %}
            <li class="right_path_logos" id="right_path_logos">
                <a href="https://t.me/colledgedsu"><img src="{% static 'src/images/telegram.svg' %}" alt="телеграм"></a>
                <a href="https://vk.com/mediaclubcollegedgu"><img src="{% static 'src/images/vk.svg' %}" alt="вк"></a>
            </li>
        </ul>
    </div>
</header>

backend/src/templates/includes/index_header.html
{% load static %}


<header class="header">
    <div class="header_content">
        <div class="header_navbar" id="header_navbar">
            <div class="nav_left_path">
                <h1><a style="color: #fff;" href="/">Колледж ДГУ</a></h1>
                <div class="header_burger" id="header_burger"></div>
            </div>
            <ul style="width: 55%;" class="nav_right_path" id="nav_right_path">
                <li><a href="/">Главная</a></li>
                {% if user.is_teacher %}
                    <li><a href="{% url 'users:teacher_profile' user.id %}">Для преподавателя</a></li>
                {% endif %}
                <li><a href="/news">Новости</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'data:schedules' %}">Расписание</a></li>
                {% else %}
                    <li><a href="https://raspisanie.dgu.ru/">Расписание</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if not user.is_teacher %}
                        <li><a href="{% url 'users:blog' %}">Преподаватели</a></li>
                    {% endif %}
                    <li><a style="color: #fff;" href="{% url 'users:profile' user.id%}">Профиль</a></li>
                {% else %}
                    <li><a style="color: #fff;" href="{% url 'users:login' %}">Вход</a></li>
                {% endif %}
                <li class="right_path_logos" id="right_path_logos">
                    <a href="https://t.me/colledgedsu"><img src="{% static 'src/images/telegram.svg' %}" alt="телеграм"></a>
                    <a href="https://vk.com/mediaclubcollegedgu"><img src="{% static 'src/images/vk.svg' %}" alt="вк"></a>
                </li>
            </ul>
        </div>
        <div class="slider" id="slider">
            <button style="padding: 0; margin-top: 12%; background: transparent; border: 0" class="slider-button prev-button"><img src="{% static 'src/images/arrow.png' %}"></button>
            <div class="slider_content">
                <div class="slide slide-left">
                    <img src="{% static 'src/images/college-2.webp' %}" alt="Левая картинка">
                </div>
                <div class="slide slide-center">
                    <img src="{% static 'src/images/college.webp' %}" alt="Центральная картинка">
                </div>
                <div class="slide slide-right">
                    <img src="{% static 'src/images/college-3.jpg' %}" alt="Правая картинка">
                </div>
            </div>
            <button style="padding: 0; margin-top: 12%; background: transparent; border: 0" class="slider-button next-button"><img src="{% static 'src/images/arrow.png' %}"></button>
        </div>
    </div>
</header>

backend/src/templates/includes/profile_header.html
{% load static %}


<header class="registration_header">
    <div class="header_navbar" id="header_navbar">
        <div class="nav_left_path">
            <h1><a style="color: #fff;" href="/">Колледж ДГУ</a></h1>
            <div class="header_burger" id="header_burger"></div>
        </div>
        <ul style="width: 65%;" class="nav_right_path" id="nav_right_path">
            <li><a href="/">Главная</a></li>
            {% if user.is_teacher %}
                <li><a href="{% url 'users:teacher_profile' user.id %}">Для преподавателя</a></li>
            {% endif %}
            <li><a href="/news">Новости</a></li>
            <li><a href="{% url 'data:schedules' %}">Расписание</a></li>
            {% if user.is_authenticated %}
                {% if not user.is_teacher %}
                    <li><a href="https://bitrix.dgu.ru/eios/Svedeniya-ob-EIOS-bibl.pdf">Библ. ресурсы</a></li>
                    <li><a href="{% url 'users:blog' %}">Преподаватели</a></li>
                {% endif %}
                <li><a style="color: #fff;" href="{% url 'users:profile' user.id%}">Профиль</a></li>
            {% else %}
                <li><a style="color: #fff;" href="{% url 'users:login' %}">Вход</a></li>
            {% endif %}
            <li class="right_path_logos" id="right_path_logos">
                <a href="https://t.me/colledgedsu"><img src="{% static 'src/images/telegram.svg' %}" alt="телеграм"></a>
                <a href="https://vk.com/mediaclubcollegedgu"><img src="{% static 'src/images/vk.svg' %}" alt="вк"></a>
            </li>
        </ul>
    </div>
</header>