backend/src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('news.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('data/', include('lessons.urls', namespace='data'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/src/lessons/urls.py
from django.urls import path

from .views import add_lecture, add_review, delete_lecture, delete_review, LectureDetail, SchedulesView


app_name = 'data'

urlpatterns = [
    path('add_lecture/', add_lecture, name='add_lecture'),
    path('add_review/<int:pk>/', add_review, name='add_review'),
    path('delete_lecture/<int:lecture_id>/', delete_lecture, name='delete_lecture'),
    path('delete_review/<int:review_id>/', delete_review, name='delete_review'),
    path('lecture/<int:pk>/', LectureDetail.as_view(), name='lecture_detail'),
    path('schedules/', SchedulesView.as_view(), name='schedules'),
]

backend/src/news/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, NewsView, NewsDetailView



urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('news/', NewsView.as_view(), name='news'),
    path('news/<slug:slug>/', NewsDetailView.as_view(), name='news_detail'),
]

backend/src/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (UserProfileView, login,
                    logout, TeacherProfile,
                    AllTeachers, PublicTeacherProfile,
                    add_personal_link, delete_personal_link,
                    delete_link)


app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('teacher-profile/<int:teacher_id>/', TeacherProfile.as_view(), name='teacher_profile'),
    path('add_personal_link/', add_personal_link, name='add_personal_link'),
    path('delete_personal_link/<int:link_id>/', delete_personal_link, name='delete_personal_link'),
    path('delete_link/<int:link_id>/', delete_link, name='delete_link'),
    path('all_teachers/', AllTeachers.as_view(), name='blog'),
    path('public_profile_teacher/<int:teacher_id>/', PublicTeacherProfile.as_view(), name='public_profile'),
    path('logout/', logout, name='logout'),
]

templates/lecture.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width">

    <title>Лекция</title>

    <link rel="stylesheet" href="{% static 'src/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'src/css/reset.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'src/images/favicon.ico' %}">


</head>
<body class="news_body">
    <header class="registration_header">
        <div class="header_navbar" id="header_navbar">
            <div class="nav_left_path">
                <h1><a style="color: #fff;" href="/">Колледж ДГУ</a></h1>
                <div class="header_burger" id="header_burger"></div>
            </div>
            <ul style="width: 55%;" class="nav_right_path" id="nav_right_path">
                <li><a href="/">Главная</a></li>
                {% if user.is_teacher %}
                    <li><a href="{% url 'users:teacher_profile' user.id %}">Для преподавателя</a></li>
                {% endif %}
                <li><a href="/news">Новости</a></li>
                <li><a href="{% url 'users:schedules' %}">Расписание</a></li>
                {% if user.is_teacher %}
                    <li><a href="{% url 'users:schedules' %}">Расписание</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if not user.is_teacher %}
                        <li><a href="https://bitrix.dgu.ru/eios/Svedeniya-ob-EIOS-bibl.pdf">Библ. ресурсы</a></li>
                        <li><a href="{% url 'users:blog' %}">Преподаватели</a></li>
                    {% endif %}
                    <li><a style="color: #fff;" href="{% url 'users:profile' user.id%}">Профиль</a></li>
                {% else %}
                    <li><a style="color: #fff;" href="{% url 'users:login' %}">Вход</a></li>
                {% endif %}
                <li class="right_path_logos" id="right_path_logos">
                    <a href="https://t.me/colledgedsu"><img src="{% static 'src/images/telegram.svg' %}" alt="телеграм"></a>
                    <a href="https://vk.com/mediaclubcollegedgu"><img src="{% static 'src/images/vk.svg' %}" alt="вк"></a>
                </li>
            </ul>
        </div>
    </header>

    <main class="one_news_main">
        <div style="width: 70%;" class="one_news">
<!--            <h1 style="position: relative;" class="one_lecture_date" id="one_lecture_date">{{ lecture.created_at|date:"d.m.Y" }}</h1>-->
            <h2 class="one_lecture_desc" id="one_lecture_desc">{{ lecture.title }}</h2>
            <p class="one_news_par" id="one_news_par">{{ lecture.description|safe }}</p>
        </div>
    </main>
    <script type="module" src="{% static 'src/scripts/index.js' %}"></script>
</body>
</html>

templates/teacher-public_profile.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width">

    <title>Страница преподавателя</title>

    <link rel="stylesheet" href="{% static 'src/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'src/css/reset.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'src/images/favicon.ico' %}">
</head>
<body>
    <header class="teacher_profile_header">
        <div class="header_navbar" id="header_navbar">
            <div class="nav_left_path">
                <h1><a style="color: #fff;" href="/">Колледж ДГУ</a></h1>
                <div class="header_burger" id="header_burger"></div>
            </div>
            <ul style="width: 55%;" class="nav_right_path" id="nav_right_path">
                <li><a href="/">Главная</a></li>
                {% if user.is_teacher %}
                    <li><a href="{% url 'users:teacher_profile' user.id %}">Для преподавателя</a></li>
                {% endif %}
                <li><a href="/news">Новости</a></li>
                <li><a href="{% url 'users:schedules' %}">Расписание</a></li>
                {% if user.is_teacher %}
                    <li><a href="{% url 'users:schedules' %}">Расписание</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if not user.is_teacher %}
                        <li><a href="https://bitrix.dgu.ru/eios/Svedeniya-ob-EIOS-bibl.pdf">Библ. ресурсы</a></li>
                        <li><a href="{% url 'users:blog' %}">Преподаватели</a></li>
                    {% endif %}
                    <li><a style="color: #fff;" href="{% url 'users:profile' user.id%}">Профиль</a></li>
                {% else %}
                    <li><a style="color: #fff;" href="{% url 'users:login' %}">Вход</a></li>
                {% endif %}
                <li class="right_path_logos" id="right_path_logos">
                    <a href="https://t.me/colledgedsu"><img src="{% static 'src/images/telegram.svg' %}" alt="телеграм"></a>
                    <a href="https://vk.com/mediaclubcollegedgu"><img src="{% static 'src/images/vk.svg' %}" alt="вк"></a>
                </li>
            </ul>
        </div>
    </header>

    <main>
        <div style="width: 80%;" class="teacher_container" id="teacher_container">
            <div class="teacher_profile" id="teacher_profile">
                <label class="input-file">
                    <img src="{% if teacher.image %} {{ teacher.image.url }} {% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                </label>
                <div class="teacher_name">
                    <h1>{{ teacher.first_name }}</h1>
                    <h2>{{ teacher.last_name }}</h2>
                </div>
                <div style="margin-bottom: 20px;" class="important_link_teacher_profile">
                    <div class='important_link_list_teacher_profile'>
                        <button class="btn_important_links_teacher_profile" id="btn_important_links">Важные ссылки</button>
                        <ul class="drop_down_link_list" id="drop_down_link_list">
                            {% for link in personal_links %}
                                <li>
                                    <a style="font-size: 18px;" href="{{ link.link }}">{{ link.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="teacher_lectures">
                <h1>Учебные материалы</h1>
                <div class="teacher_line"></div>
                {% if lectures %}
                    {% for lecture in lectures %}
                        <ul style="grid-template-columns: repeat(1, 1fr);" class="all_lectures">
                            <li style="max-height: 200px; overflow: hidden;" class="lecture">
                                <h1 style="line-height: 0.9;">{{ lecture.title }}</h1>
                                <p>
                                    <button id="podrobnee">
                                        <a style="color: #fff" href="{% url 'users:lecture_detail' lecture.pk %}">Подробнее</a></b>
                                    </button>
                                </p>
                            </li>
                            <form action="{% url 'users:add_review' pk=lecture.id %}" enctype="multipart/form-data" autocomplete="off" method="post">
                                {% csrf_token %}
                                <section class="lectures_comments">
                                    <button class="show_comment" id="show_comment_{{ lecture.id }}">Показать комментарии ({{ lecture.get_review|length }})</button>
                                    <div class="comments_container" id="comments_container">
                                        <div class="show_all_comments" id="show_all_comments">
                                            {% for review in lecture.get_review %}
                                                <div class="comment">
                                                    <img class="user_ava" src="{% if review.name.image %}{{ review.name.image.url }}{% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                                                    <div class="user_data">
                                                        <div class="left_side">
                                                            <h1 class="user_name" id="user_name_{{ review.name.id }}">
                                                                {{ review.name.first_name }} {{ review.name.last_name }}
                                                            </h1>
                                                            <p class="user_comment">{{ review.text }}</p>
                                                            {% if review.file %}
                                                                <a style="margin-top: 10px; text-decoration: underline; color: #17A2B8; font-family: 'Inter', sans-serif; font-size: 12px;" href="{{ review.file.url }}">Посмотреть прикрепленный файл</a>
                                                            {% endif %}
                                                            <h2 style="margin-top: 15px" class="answer_comment">Ответить</h2>
                                                        </div>
                                                        <div class="right_side">
                                                            {% if review.name == user %}
                                                                <a href="{% url 'users:delete_review' review.pk %}"><b>&#10006;</b></a>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="publish_comment">
                                            <img class="my_ava"
                                                 src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                                            <div class="my_data">
                                                <div class="my_name_cont">
                                                    <h1 class="my_name">{{ user.first_name }} {{ user.last_name }}</h1>
                                                    {{ form.text }}
                                                    {{ form.file }}
                                                </div>
                                                <button style="border: 0; background-color: #fff" type="submit" class="publish_btn"></button>
                                            </div>
                                        </div>
                                </section>
                            </form>
                        </ul>
                    {% endfor %}
                {% else %}
                    <h2>Учебных материалов нет</h2>
                {% endif %}
            </div>
        </div>
    </main>
    <script type="module" src="{% static 'src/scripts/index.js' %}"></script>
    <script type="module" src="{% static 'src/scripts/teacher-profile-dropdown.js' %}"></script>
    <script type="module" src="{% static 'src/scripts/drop_comment.js' %}"></script>
</body>
</html>