backend/src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('news.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('data/', include('lessons.urls', namespace='data'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/src/lessons/urls.py
from django.urls import path

from .views import add_lecture, add_review, delete_lecture, delete_review, LectureDetail, SchedulesView


app_name = 'data'

urlpatterns = [
    path('add_lecture/', add_lecture, name='add_lecture'),
    path('add_review/<int:pk>/', add_review, name='add_review'),
    path('delete_lecture/<int:lecture_id>/', delete_lecture, name='delete_lecture'),
    path('delete_review/<int:review_id>/', delete_review, name='delete_review'),
    path('lecture/<int:pk>/', LectureDetail.as_view(), name='lecture_detail'),
    path('schedules/', SchedulesView.as_view(), name='schedules'),
]

backend/src/news/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, NewsView, NewsDetailView



urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('news/', NewsView.as_view(), name='news'),
    path('news/<slug:slug>/', NewsDetailView.as_view(), name='news_detail'),
]

backend/src/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (UserProfileView, login,
                    logout, TeacherProfile,
                    AllTeachers, PublicTeacherProfile,
                    add_personal_link, delete_personal_link,
                    delete_link)


app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('teacher-profile/<int:teacher_id>/', TeacherProfile.as_view(), name='teacher_profile'),
    path('add_personal_link/', add_personal_link, name='add_personal_link'),
    path('delete_personal_link/<int:link_id>/', delete_personal_link, name='delete_personal_link'),
    path('delete_link/<int:link_id>/', delete_link, name='delete_link'),
    path('all_teachers/', AllTeachers.as_view(), name='blog'),
    path('public_profile_teacher/<int:teacher_id>/', PublicTeacherProfile.as_view(), name='public_profile'),
    path('logout/', logout, name='logout'),
]

backend/src/news/models.py
from django.db import models
from datetime import date
from django.urls import reverse
from django.utils import timezone
from datetime import datetime


class News(models.Model):
    title = models.CharField('Название', max_length=150)
    description = models.CharField('Описание')
    image = models.ImageField('Изображение')
    slug = models.SlugField(max_length=150, unique=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

backend/src/news/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView, DetailView
from django.http import JsonResponse
from .models import News


class IndexView(TemplateView):
    template_name = 'pages/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news'] = News.objects.order_by('-created_at')[:3]
        return context


class NewsView(TemplateView):
    template_name = 'pages/news.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_news'] = News.objects.order_by('-created_at')
        return context


class NewsDetailView(DetailView):
    model = News
    slug_field = "slug"
    template_name = 'pages/one-news.html'

backend/src/templates/pages/all-teachers.html
{% extends 'bases/base.html' %}
{% load static %}


{% block layout %}
    <main>
       <ul style="margin-bottom: 50px;" class="all_teachers_container" id="all_teachers_container">
           {% for teacher in all_teachers %}
                <li>
                   <img src="{% if teacher.image %} {{ teacher.image.url }} {% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}" alt="">
                    <h1>{{ teacher.first_name }} <br> {{ teacher.last_name }}</h1>
                    <button><a href="{% url 'users:public_profile' teacher.id %}">Смотреть лекции</a></button>
                </li>
           {% endfor %}
       </ul>
    </main>

    <script type="module" src="{% static 'src/scripts/index.js' %}"></script>
{% endblock %}

backend/src/templates/pages/index.html
{% extends 'bases/index_base.html' %}
{% load static %}


{% block layout %}
    <main class="main">
        <div class="main_content">
            <div class="main_about_college">
                <div class="top_info">
                    <h1>О колледже</h1>
                </div>
                <ul class="bottom_info" id="bottom_info">
                    <li class="bottom_info_left">
                        <div class="bottom_info_line"></div>
                        <p>
                            Дагестанский государственный университет<br>является одним из крупнейших вузов России,<br>
                            который был создан в 1931 году.
                        </p>
                    </li>
                    <li class="bottom_info_right">
                        <p>
                            Колледж ДГУ создан в 2013 году.<br>
                            Это структурное подразделение Дагестанского<br>
                            госудраственого университета, обеспечивающее высокое качество подготовки<br>
                            специалистов среднего звена для удовлетворения потребностей общества в области<br>
                            права, охраны окружающей среды и природоиспользования, действующее на основании<br>
                            лицензии университета на право ведения образовательной деятельности.
                        </p>
                    </li>
                </ul>
            </div>
            <div class="main_news" id="main_news">
                <h1 class="main_news_title">Что нового?</h1>
                <ul class="main_all_news" id="main_all_news">
                    {% for new in news %}
                        <li class="main_news_item item1">
                            <img src="{{ new.image.url }}" alt="">
                            <div class="news_date">{{ new.created_at|date:"d.m.Y" }}</div>
                            <p class="news_desc"><a href="{{ new.get_absolute_url }}">{{ new.title }}</a></p>
                        </li>
                    {% endfor %}
                </ul>
                <button><a href="/news">Больше новостей</a></button>
            </div>
    </main>
    {% include 'includes/footer.html' %}
    <script type="module" src="{% static 'src/scripts/index.js' %}"></script>
{% endblock %}

backend/src/templates/pages/lecture.html
{% extends 'bases/base.html' %}
{% load static %}


{% block layout %}
    <main class="one_news_main">
        <div style="width: 70%;" class="one_news">
            <h1 style="position: relative;" class="one_lecture_date" id="one_lecture_date">{{ lecture.created_at|date:"d.m.Y" }}</h1>
            <h2 class="one_lecture_desc" id="one_lecture_desc">{{ lecture.title }}</h2>
            <p class="one_news_par" id="one_news_par">{{ lecture.description|safe }}</p>
        </div>
    </main>
    <script type="module" src="{% static 'src/scripts/index.js' %}"></script>
{% endblock %}

backend/src/templates/pages/new_lesson.html
{% extends 'bases/base.html' %}
{% load static %}


{% block layout %}
    {% if user.is_teacher %}
        <main>
            <form style="width: 90%;" class="main_blog_form" method="post">
                <h1>Ваш материал</h1>
                {% csrf_token %}
                <input type="text" name="title" placeholder="Название лекции">
                <div class="ckeditor">{{ form.media }}{{ form.description }}</div>
                <div class="add_lectures_droplist" id="add_lectures_droplist">
                    {{ form.facult.label_tag }} {{ form.facult }}
                    {{ form.course.label_tag }} {{ form.course }}
                    {{ form.group.label_tag }} {{ form.group }}
                </div>
                <button class="publish_lecture">Опубликовать</button>
            </form>
        </main>
    {% else %}
        <h1>Ты не преподаватель!</h1>
    {% endif %}
    <script type="module" src="{% static 'src/scripts/index.js' %}"></script>
{% endblock %}

backend/src/templates/pages/profile.html
{% extends 'bases/base_for_profile.html' %}
{% load link_filter %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7" style="margin: 0 auto; position: relative;">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'users:profile' user.id %}" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="userAvatar" name="image" size="50">
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                изображение</label>
                        </div>
                    </div>
                </div>

                {% if not user.is_teacher %}
                    {% for schedule in schedules %}
                        <a style="margin: 10px;" href="{{ schedule.schedule.url }}">Расписание</a>
                    {% endfor %}
                {% endif %}
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 10px; margin-bottom: 20px;">
                        <a href="{% url 'users:logout' %}" class="btn btn-info btn-block">Выйти</a>
                    </div>
                </div>
            </form>
            <form action="{% url 'users:add_personal_link' %}" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {% if user.is_teacher %}
                <div style="margin-bottom: 20px;" class="important_link">
                    <div class='important_link_list'>
                        <button class="btn_important_links" id="btn_important_links">Важные ссылки</button>
                        <ul class="drop_down_link_list" id="drop_down_link_list">
                            {% if private_personal_links %}
                                <div style="margin: 0 auto;"><b>Только у меня</b></div>
                            {% for link in private_personal_links %}
                            <li>
                                <a style="font-size: 18px;" href="{{ link.link }}">{{ link.title }}</a>
                                <div class="actions_with_links">
                                    <div class="dropdown_krestik">
                                        <a style="text-decoration: none;"
                                           href="{% url 'users:delete_personal_link' link.pk %}">
                                            &#10006;
                                        </a>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                            {% endif %}
                            {% if personal_links %}
                            <div style="margin: 0 auto;"><b>Публичные</b></div>
                            {% for link in personal_links %}
                            <li>
                                <a style="font-size: 18px;" href="{{ link.link }}">{{ link.title }}</a>
                                <div class="actions_with_links">
                                    <div class="dropdown_krestik">
                                        <a style="text-decoration: none;"
                                           href="{% url 'users:delete_personal_link' link.pk %}">
                                            &#10006;
                                        </a>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                    <div class='important_link_add'>
                        <button class="btn_add_link" id="btn_add_link">Добавить ссылку</button>
                        <div class="add_link" id="add_link">
                            <div style="border: 1px;">{{ form.personal_link_form.title }}</div>
                            <div style="border: 1px;">{{ form.personal_link_form.link }}</div>
                            {{ form.personal_link_form.facult }}
                            {{ form.personal_link_form.course }}
                            {{ form.personal_link_form.group }}
                            <div>{{ form.personal_link_form.private }} Только у меня</div>
                            <input type="submit" class="publish_link" value="Опубликовать">
                        </div>
                    </div>
                </div>
                {% endif %}
            </form>
            <form action="{% url 'users:profile' user.id %}" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {% if user.is_teacher %}
                <div>
                    <ul class="teacher_profile_droplist">
                        <li>{{ form.link_form.facult.label_tag }}</li>
                        <li>{{ form.link_form.facult }}</li>
                    </ul>
                    <ul class="teacher_profile_droplist">
                        <li>{{ form.link_form.course.label_tag }}</li>
                        <li>{{ form.link_form.course }}</li>
                    </ul>
                    <ul class="teacher_profile_droplist">
                        <li>{{ form.link_form.group.label_tag }}</li>
                        <li>{{ form.link_form.group }}</li>
                    </ul>
                    <ul>{{ form.link_form.link.label_tag }} {{ form.link_form.link }}</ul>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input style="margin-bottom: 40px;" class="btn btn-info btn-block" type="submit"
                               value="Отправить">
                    </div>
                </div>
                {% endif %}
            </form>
                {% if user.is_teacher %}
                    <div class="msg_teacher_cont">
                        <button class="btn_teacher_message" id="btn_message">Мои сообщения</button>
                        <ul class="drop_down_msg_list" id="drop_down_msg_list">
                            {% for link in links %}
                            {% if link.link %}
                                <li>
                                    <div>
                                        {{ link.link|format_text|safe }}
                                    </div>
                                    <a style="text-decoration: none;" href="{% url 'users:delete_link' link.pk %}">
                                        &#10006;
                                    </a>
                                </li>
                            {% endif %}
                            {% endfor %}
                    </div>
                {% else %}
                    <div class="msg_student_cont" id="msg_student_cont">
                        <button class="btn_message" id="btn_message"></button>
                        <ul class="drop_down_msg_list_student" id="drop_down_msg_list">
                            {% for link in links %}
                            {% if link.link %}
                                <li>
                                    <p><span>Отправитель:</span>
                                        <a href="{% url 'users:public_profile' link.teacher.id %}">
                                            {{link.teacher.get_full_name }}
                                        </a> | <span style="font-size: 12px;">{{ link.created_at|date:"d.m.Y"}}</span>
                                    </p>
                                    <div>
                                        {{ link.link|format_text|safe }}
                                    </div>
                                </li>
                            {% endif %}
                            {% endfor %}
                    </div>
                {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

backend/src/templates/pages/teacher-profile.html
{% extends 'bases/base.html' %}
{% load static %}


{% block layout %}
    {% if user.is_teacher %}
    <main>
        <div style="width: 80%;" class="teacher_container" id="teacher_container">
            <div class="teacher_profile">
                <label class="input-file">
                    <img src="{% if teacher.image %} {{ teacher.image.url }} {% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                </label>
                <div class="teacher_name">
                    <h1>{{ teacher.first_name }}</h1>
                    <h2>{{ teacher.last_name }}</h2>
                </div>
            </div>
            <div class="teacher_lectures">
                <h1>Учебные материалы</h1>
                <div class="teacher_line"></div>
                {% if lectures %}
                    {% for lecture in lectures %}
                        <ul style="grid-template-columns: repeat(1, 1fr);" class="all_lectures">
                            <p class="obama">
                                <strong>Направление:</strong> {{ lecture.facult }} {{ lecture.course }}
                                {% if lecture.group %} {{ lecture.group }} {% endif %}
                            </p>
                            <li style="max-height: 200px; overflow: hidden;" class="lecture">
                                <button><a href="{% url 'data:delete_lecture' lecture.pk %}">&#10006;</a></button>
                                <h1 style="line-height: 0.9;">{{ lecture.title }}</h1>
                                <p>
                                    <button id="podrobnee">
                                        <b style="margin-top: 10px; border: 5; border-color: transparent;">
                                            <a style="color: #fff" href="{% url 'data:lecture_detail' lecture.pk %}">Подробнее</a></b>
                                    </button>
                                </p>
                            </li>
                            <form action="{% url 'data:add_review' pk=lecture.id %}" autocomplete="off" method="post">
                                {% csrf_token %}
                                <section class="lectures_comments">
                                    <button class="show_comment" id="show_comment_{{ lecture.id }}">Показать комментарии ({{ lecture.get_review|length }})
                                    </button>
                                    <div class="comments_container" id="comments_container">
                                        <div class="show_all_comments" id="show_all_comments">
                                            {% for review in lecture.get_review %}
                                                <div class="comment">
                                                    <img class="user_ava"
                                                         src="{% if review.name.image %}{{ review.name.image.url }}{% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                                                    <div class="user_data">
                                                        <div class="left_side">
                                                            <h1 class="user_name" id="user_name_{{ review.name.id }}">
                                                                {{ review.name.first_name }} {{ review.name.last_name }}
                                                            </h1>
                                                            <p class="user_comment">{{ review.text }}</p>
                                                            <h2 class="answer_comment">Ответить</h2>
                                                        </div>
                                                        <div class="right_side">
                                                            {% if review.name == user %}
                                                                <a href="{% url 'data:delete_review' review.pk %}"><b>&#10006;</b></a>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="publish_comment">
                                            <img class="my_ava"
                                                 src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                                            <div class="my_data">
                                                <div class="my_name_cont">
                                                    <h1 class="my_name">{{ user.first_name }} {{ user.last_name }}</h1>
                                                    {{ form.text }}
                                                </div>
                                                <button style="border: 0; background-color: #fff" type="submit"
                                                        class="publish_btn"></button>
                                            </div>
                                        </div>
                                </section>
                            </form>
                        </ul>
                    {% endfor %}
                {% else %}
                    <h2>Учебных материалов нет</h2>
                {% endif %}
                <div class="add_lecture_cont">
                    <button class="add_lecture">
                        <a style="margin-bottom: 40px;" href="{% url 'data:add_lecture' %}">Добавить материал</a>
                    </button>
                </div>
            </div>
        </div>
    </main>
    {% else %}
        <h1>Ты не преподаватель!</h1>
    {% endif %}

    <script type="module" src="{% static 'src/scripts/index.js' %}"></script>
    <script type="module" src="{% static 'src/scripts/drop_comment.js' %}"></script>
{% endblock %}

backend/src/templates/pages/teacher-public_profile.html
{% extends 'bases/base.html' %}
{% load static %}


{% block layout %}
    <main>
        <div style="width: 80%;" class="teacher_container" id="teacher_container">
            <div class="teacher_profile" id="teacher_profile">
                <label class="input-file">
                    <img src="{% if teacher.image %} {{ teacher.image.url }} {% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                </label>
                <div class="teacher_name">
                    <h1>{{ teacher.first_name }}</h1>
                    <h2>{{ teacher.last_name }}</h2>
                </div>
                <div style="margin-bottom: 20px;" class="important_link_teacher_profile">
                    <div class='important_link_list_teacher_profile'>
                        <button class="btn_important_links_teacher_profile" id="btn_important_links">Важные ссылки</button>
                        <ul class="drop_down_link_list" id="drop_down_link_list">
                            {% for link in personal_links %}
                                <li>
                                    <a style="font-size: 18px;" href="{{ link.link }}">{{ link.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="teacher_lectures">
                <h1>Учебные материалы</h1>
                <div class="teacher_line"></div>
                {% if lectures %}
                    {% for lecture in lectures %}
                        <ul style="grid-template-columns: repeat(1, 1fr);" class="all_lectures">
                            <li style="max-height: 200px; overflow: hidden;" class="lecture">
                                <h1 style="line-height: 0.9;">{{ lecture.title }}</h1>
                                <p>
                                    <button id="podrobnee">
                                        <a style="color: #fff" href="{% url 'data:lecture_detail' lecture.pk %}">Подробнее</a></b>
                                    </button>
                                </p>
                            </li>
                            <form action="{% url 'data:add_review' pk=lecture.id %}" enctype="multipart/form-data" autocomplete="off" method="post">
                                {% csrf_token %}
                                <section class="lectures_comments">
                                    <button class="show_comment" id="show_comment_{{ lecture.id }}">Показать комментарии ({{ lecture.get_review|length }})</button>
                                    <div class="comments_container" id="comments_container">
                                        <div class="show_all_comments" id="show_all_comments">
                                            {% for review in lecture.get_review %}
                                                <div class="comment">
                                                    <img class="user_ava" src="{% if review.name.image %}{{ review.name.image.url }}{% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                                                    <div class="user_data">
                                                        <div class="left_side">
                                                            <h1 class="user_name" id="user_name_{{ review.name.id }}">
                                                                {{ review.name.first_name }} {{ review.name.last_name }}
                                                            </h1>
                                                            <p class="user_comment">{{ review.text }}</p>
                                                            {% if review.file %}
                                                                <a style="margin-top: 10px; text-decoration: underline; color: #17A2B8; font-family: 'Inter', sans-serif; font-size: 12px;" href="{{ review.file.url }}">Посмотреть прикрепленный файл</a>
                                                            {% endif %}
                                                            <h2 style="margin-top: 15px" class="answer_comment">Ответить</h2>
                                                        </div>
                                                        <div class="right_side">
                                                            {% if review.name == user %}
                                                                <a href="{% url 'data:delete_review' review.pk %}"><b>&#10006;</b></a>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="publish_comment">
                                            <img class="my_ava"
                                                 src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'src\images\default_avatar.jpg' %} {% endif %}">
                                            <div class="my_data">
                                                <div class="my_name_cont">
                                                    <h1 class="my_name">{{ user.first_name }} {{ user.last_name }}</h1>
                                                    {{ form.text }}
                                                    {{ form.file }}
                                                </div>
                                                <button style="border: 0; background-color: #fff" type="submit" class="publish_btn"></button>
                                            </div>
                                        </div>
                                </section>
                            </form>
                        </ul>
                    {% endfor %}
                {% else %}
                    <h2>Учебных материалов нет</h2>
                {% endif %}
            </div>
        </div>
    </main>
    <script type="module" src="{% static 'src/scripts/index.js' %}"></script>
    <script type="module" src="{% static 'src/scripts/teacher-profile-dropdown.js' %}"></script>
    <script type="module" src="{% static 'src/scripts/drop_comment.js' %}"></script>
{% endblock %}